name: 'Geekbot Slack Notifications'
description: 'Notify Geekbot Weekly Report to Slack'
inputs:
  geekbot_api_key:
    description: 'Geekbot API Key'
    required: true
    default: 'World'
  question_ids:
    description: 'Geekbot Question Ids'
    required: true
  standup_id:
    description: 'Geekbot Stabdup Id'
    required: true
  members:
    description: 'Geekbot Member Id'
    required: true
outputs:
  slack_format_json:
    description: 'Slack format json'
runs:
  using: 'node16'
  main: 'index.js'
